title: Abbas
description: Just another blog!

url: http://github.com/a66as
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Recent Posts
    url: /index.html
  - title: About
    url: /about

social:
  github: a66as
  twitter: a66askhan
  facebook: a66as
  email: 

google_analytics: "UA-58263416-1"
